[package]
name = "syntree"
version = "0.13.2"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2021"
rust-version = "1.65.0"
description = "A memory efficient syntax tree for language developers."
documentation = "https://docs.rs/syntree"
readme = "README.md"
homepage = "https://github.com/udoprog/syntree"
repository = "https://github.com/udoprog/syntree"
license = "MIT/Apache-2.0"
keywords = ["language", "syntax-tree"]
categories = ["parsing"]

# Avoid loading benches from the benches directory so we can add more
# dependencies in there which would otherwise hog down testing this crate.
autobenches = false

[dev-dependencies]
anyhow = "1.0.69"
thiserror = "1.0.38"
codespan-reporting = "0.11.1"

[workspace] 
members = [
    "benches",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
