[package]
name = "syntree"
version = "0.10.3"
edition = "2021"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/syntree"
homepage = "https://github.com/udoprog/syntree"
documentation = "https://docs.rs/syntree"
keywords = ["language", "syntax-tree"]
categories = ["parsing"]
description = """
A memory efficient syntax tree for language developers.
"""

# Avoid loading benches from the benches directory so we can add more
# dependencies in there which would otherwise hog down testing this crate.
autobenches = false

[features]
# Use a u32 instead of usize for indexes which reduces memory use on larger than
# 32-bit platforms.
u32 = []

[dev-dependencies]
anyhow = "1.0"
thiserror = "1.0"
codespan-reporting = "0.11.1"

[workspace] 
members = [
    "benches",
]
