[package]
name = "benches"
version = "0.0.0"
edition = "2021"
publish = false

[dev-dependencies]
criterion = "0.4.0"
rand = "0.8.5"

# benchmark targets
syntree = { path = ".." }
rowan = "0.15.11"

[[bench]]
name = "comparisons"
path = "comparisons.rs"
harness = false
